### ISSUE TITLE
UPP gets stuck building the backbone alignment

### ISSUE THREAD

**Issue by kleempoel** [smirarab/sepp#113]
Hi,
I'm using UPP to align DNA sequences of several plant genes and, for some genes, it got stuck building the backbone alignment.

> exhaustive_upp.py (line 120):     INFO: Generating pasta backbone alignment and tree. 

This was the last line in the log, with nothing happening for days. 
I compared genes that passed alignment and those that failed. The only thing I found was that the ratio between the longest and mean length of sequences was higher for failing genes. But some aligned genes had a high ratio too. 

I am using SEPP version 4.5.1 and python 3.8. This issue doesn't seem to happen with version 4.3.12 and python 2.7

I'm attaching 4 .fasta files, 2 that proceeded to alignment 2 other that failed.
[upp_issue.zip](https://github.com/smirarab/sepp/files/6700202/upp_issue.zip)

Do you know what could cause this issue?

Thank you in advance for your help

**Comment by smirarab** [comment]
Let me see if I can reproduce.

In the meantime, there are several things you can try. 

1. Using one of these two options, you can control the minimum and maximum length for what is considered full length. Every thing larger or smaller is added at the end. I think reducing Nmax to something like 500 may do the trick. (e.g., `-R 200 500`) 

  -R "Nmin Nmax", --full_length_range "Nmin Nmax"
                        Only consider sequences with lengths within Nmin and
                        Nmax
  -M N, --median_full_length N
                        Consider all fragments that are 25% longer or shorter
                        than N to be excluded from the backbone. If value is
                        -1, then UPP will use the median of the sequences as
                        the median full length [default: None]
  -T N, --backbone_threshold N
                        Only consider sequences with lengths within (1-N)*M
                        and (1+N)*M as full-length, where M is the median
                        length of the full-length sequence given by the -M
                        option and N is the percentage given by the -T
                        option.[default: 0.25]


2. The backbone generation using  is what is not finishing here. Using the following option, you can reduce the backbone size to something like 1000. 

  -B N, --backboneSize N
                        (Optional) size of backbone set. If no backbone tree
                        and alignment is given, the sequence file will be
                        randomly split into a backbone set (size set to N) and
                        query set (remaining sequences), [default:
                        min(1000,input size)]

**Comment by smirarab** [comment]
I tried to reproduce the error but could not. I used UPP version 4.3.17 and Python version 3.7.6. I ran on failed_1.fasta and it ran successfully to completion. I suggest you try running again, perhaps using -x to limit the number of cores. Maybe something funky happened with the number of cores. Also, see if you can update to 4.3.17. 

In particular, for python 3.8 compatibility, changes in versions 4.315 and 4.3.17 are important. So that may be the reason for failure.

**Comment by kleempoel** [comment]
Hi Siavash,
thank you for your quick response. 
I should have specified that I was using `-M -1` to define the size of the backbone alignment and tree. But it only gets stuck with UPP 4.5.1, there is no issue with 4.3.12.

Using the default `run_upp.py -s <unaligned_sequences>`, equivalent to `-B 1000` if I understood correctly, there is indeed no problem.

Thanks

**Comment by smirarab** [comment]
I see. I am now testing `-M -1` with 4.3.17 and later with 4.5.1. I will reopen if I can reproduce.
