### ISSUE TITLE
Problem with SEPP on conda?

### ISSUE THREAD

**Issue by berkelem** [smirarab/sepp#114]
Hi,
During development for BUSCO I noticed that SEPP fails without an error message. This only happens when using conda however. I tried with the non-conda installation from Github and it worked fine. Both runs used SEPP 4.3.10.

The first run was in a dedicated conda environment:

`conda create -n sepp_4310 -c conda-forge -c bioconda sepp=4.3.10`

Once this environment is activated I created an output folder `conda_spec_version`, then ran the following command with the attached files:

`run_sepp.py --cpu 10 --outdir $(pwd)/conda_spec_version/placement_files -t tree.bacteria_odb10.2019-12-16.nwk -r tree_metadata.bacteria_odb10.2019-12-16.txt -a supermatrix.aln.bacteria_odb10.2019-12-16.faa -f marker_genes.fasta -F 15 -m amino -p conda_spec_version/tmp`

The output log is here: 
[sepp_conda_specific.log](https://github.com/smirarab/sepp/files/6932642/sepp_conda_specific.log)

You can see that the run failed with the following traceback:

> multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/scratch/berkeley/anaconda3/envs/sepp_4310/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/scratch/berkeley/anaconda3/envs/sepp_4310/lib/python3.8/site-packages/sepp/scheduler.py", line 74, in __call__
    return self.run()
  File "/scratch/berkeley/anaconda3/envs/sepp_4310/lib/python3.8/site-packages/sepp/jobs.py", line 150, in run
    raise JobError("\n".join([
sepp.scheduler.JobError: The following execution failed:
/scratch/berkeley/anaconda3/envs/sepp_4310/bin/pplacer --out-dir /scratch/berkeley/BUSCO/busco_v5_dev/sepp_problem/conda_spec_version/tmp/output.a57v4kd5/root/P_13 -j 1 -r /scratch/berkeley/BUSCO/busco_v5_dev/sepp_problem/conda_spec_version/tmp/output.a57v4kd5/root/P_13/pplacer.backbone.jgeduzld.fasta -s tree_metadata.bacteria_odb10.2019-12-16.txt -t /scratch/berkeley/BUSCO/busco_v5_dev/sepp_problem/conda_spec_version/tmp/output.a57v4kd5/root/P_13/pplacer.tree.hu6sa8z0.tre --groups 10 /scratch/berkeley/BUSCO/busco_v5_dev/sepp_problem/conda_spec_version/tmp/output.a57v4kd5/root/P_13/pplacer.extended.0.8oaqzlrd.fasta
No error messages available
"""
>
> The above exception was the direct cause of the following exception:
>
> Traceback (most recent call last):
  File "/scratch/berkeley/anaconda3/envs/sepp_4310/bin/run_sepp.py", line 26, in <module>
    ExhaustiveAlgorithm().run()
  File "/scratch/berkeley/anaconda3/envs/sepp_4310/lib/python3.8/site-packages/sepp/algorithm.py", line 174, in run
    if (not JobPool().wait_for_all_jobs()):
  File "/scratch/berkeley/anaconda3/envs/sepp_4310/lib/python3.8/site-packages/sepp/scheduler.py", line 365, in wait_for_all_jobs
    result.get()
  File "/scratch/berkeley/anaconda3/envs/sepp_4310/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
sepp.scheduler.JobError: The following execution failed:
/scratch/berkeley/anaconda3/envs/sepp_4310/bin/pplacer --out-dir /scratch/berkeley/BUSCO/busco_v5_dev/sepp_problem/conda_spec_version/tmp/output.a57v4kd5/root/P_13 -j 1 -r /scratch/berkeley/BUSCO/busco_v5_dev/sepp_problem/conda_spec_version/tmp/output.a57v4kd5/root/P_13/pplacer.backbone.jgeduzld.fasta -s tree_metadata.bacteria_odb10.2019-12-16.txt -t /scratch/berkeley/BUSCO/busco_v5_dev/sepp_problem/conda_spec_version/tmp/output.a57v4kd5/root/P_13/pplacer.tree.hu6sa8z0.tre --groups 10 /scratch/berkeley/BUSCO/busco_v5_dev/sepp_problem/conda_spec_version/tmp/output.a57v4kd5/root/P_13/pplacer.extended.0.8oaqzlrd.fasta
No error messages available
Traceback (most recent call last):
  File "/scratch/berkeley/anaconda3/envs/sepp_4310/lib/python3.8/site-packages/sepp/jobs.py", line 150, in run
    raise JobError("\n".join([
sepp.scheduler.JobError: The following execution failed:
/scratch/berkeley/anaconda3/envs/sepp_4310/bin/pplacer --out-dir /scratch/berkeley/BUSCO/busco_v5_dev/sepp_problem/conda_spec_version/tmp/output.a57v4kd5/root/P_14 -j 1 -r /scratch/berkeley/BUSCO/busco_v5_dev/sepp_problem/conda_spec_version/tmp/output.a57v4kd5/root/P_14/pplacer.backbone.hhpu0mxq.fasta -s tree_metadata.bacteria_odb10.2019-12-16.txt -t /scratch/berkeley/BUSCO/busco_v5_dev/sepp_problem/conda_spec_version/tmp/output.a57v4kd5/root/P_14/pplacer.tree.zjuzzgre.tre --groups 10 /scratch/berkeley/BUSCO/busco_v5_dev/sepp_problem/conda_spec_version/tmp/output.a57v4kd5/root/P_14/pplacer.extended.3.2hhcvyrf.fasta
No error messages available
Traceback (most recent call last):
  File "/scratch/berkeley/anaconda3/envs/sepp_4310/lib/python3.8/site-packages/sepp/jobs.py", line 150, in run
    raise JobError("\n".join([
sepp.scheduler.JobError: The following execution failed:
/scratch/berkeley/anaconda3/envs/sepp_4310/bin/pplacer --out-dir /scratch/berkeley/BUSCO/busco_v5_dev/sepp_problem/conda_spec_version/tmp/output.a57v4kd5/root/P_13 -j 1 -r /scratch/berkeley/BUSCO/busco_v5_dev/sepp_problem/conda_spec_version/tmp/output.a57v4kd5/root/P_13/pplacer.backbone.jgeduzld.fasta -s tree_metadata.bacteria_odb10.2019-12-16.txt -t /scratch/berkeley/BUSCO/busco_v5_dev/sepp_problem/conda_spec_version/tmp/output.a57v4kd5/root/P_13/pplacer.tree.hu6sa8z0.tre --groups 10 /scratch/berkeley/BUSCO/busco_v5_dev/sepp_problem/conda_spec_version/tmp/output.a57v4kd5/root/P_13/pplacer.extended.0.8oaqzlrd.fasta
No error messages available

However, if I change the `run_sepp.py` executable to the one installed from the cloned Github repo and run it again (writing to a different output folder `home_version`) as follows

`~/.virtualenvs/busco_env/bin/run_sepp.py --cpu 10 --outdir $(pwd)/home_version/placement_files -t tree.bacteria_odb10.2019-12-16.nwk -r tree_metadata.bacteria_odb10.2019-12-16.txt -a supermatrix.aln.bacteria_odb10.2019-12-16.faa -f marker_genes.fasta -F 15 -m amino -p home_version/tmp`

the run completes successfully. Log output is here: 
[sepp_home.log](https://github.com/smirarab/sepp/files/6932692/sepp_home.log)

Everything else about the two runs is identical: python=3.8.10, hmmer=3.1b2 etc

Can you shed any light on what is going on? Why does the conda run fail while the cloned installation runs successfully?

[sepp_bug_files.tar.gz](https://github.com/smirarab/sepp/files/6932620/sepp_bug_files.tar.gz)

**Comment by sjanssen2** [comment]
Hi @berkelem,
looks like SEPP fails with the first call to `pplacer`. What happens when you activate `sepp_4310` and manually execute the failing call: 
``` 
/scratch/berkeley/anaconda3/envs/sepp_4310/bin/pplacer --out-dir /scratch/berkeley/BUSCO/busco_v5_dev/sepp_problem/conda_spec_version/tmp/output.a57v4kd5/root/P_13 -j 1 -r /scratch/berkeley/BUSCO/busco_v5_dev/sepp_problem/conda_spec_version/tmp/output.a57v4kd5/root/P_13/pplacer.backbone.jgeduzld.fasta -s tree_metadata.bacteria_odb10.2019-12-16.txt -t /scratch/berkeley/BUSCO/busco_v5_dev/sepp_problem/conda_spec_version/tmp/output.a57v4kd5/root/P_13/pplacer.tree.hu6sa8z0.tre --groups 10 /scratch/berkeley/BUSCO/busco_v5_dev/sepp_problem/conda_spec_version/tmp/output.a57v4kd5/root/P_13/pplacer.extended.0.8oaqzlrd.fasta
```

(temporary files might have been already deleted, thus you might have to first re-execute the failing SEPP command)

How much memory is available on your machine. Could you maybe append the failing command with `/usr/bin/time -v` and paste the log?

**Comment by berkelem** [comment]
Hi, apologies for the delayed reply - I was away.

I entered the command as you wrote it and got a `Segmentation fault (core dumped)` error immediately.

**Comment by berkelem** [comment]
After a bit more investigation along with our sys admin it turns out the problem may be with the particular machine I was using being unable to handle the instructions from the bundled pplacer binary in the SEPP conda package. The pplacer binary depends on an old version of ocaml and ocaml is not great at keeping backward compatibility. Hence it doesn't work on that particular machine. 

We have managed to get it to work on several other machines though, so there doesn't seem to be anything critical with the SEPP package. I'll close this issue.

**Comment by cmkobel** [comment]
I get the same error message (see attached log for full details: [sepp_err.log](https://github.com/smirarab/sepp/files/11069531/sepp_err.log))

I installed busco 5.4.6 (same with 5.4.5 and 5.4.4 for that matter), and when busco runs sepp, I get.

```
[18:09:03] alignment.py (line 568):     INFO: Merging extension sto file (/home/axodines/assemblycomparator2/tests/MAGs/results_ac2/samples/Treatment_LowE.metabat.461/busco/auto_lineage/run_bacteria_odb10/sepp_tmp_files/output.gv3gkm6m/root/P_9/A_9_0/FC_9_0_0/hmmalign.results.pz43t2c5) into base alignment (/home/axodines/assemblycomparator2/tests/MAGs/results_ac2/samples/Treatment_LowE.metabat.461/busco/auto_lineage/run_bacteria_odb10/sepp_tmp_files/output.gv3gkm6m/root/P_9/A_9_0/hmmbuild.input.upeefbxo.fasta).
[18:09:03] exhaustive.py (line 153):     INFO: Merging sub-alignments for placement problem : P_10.
[18:09:03] exhaustive.py (line 153):     INFO: Merging sub-alignments for placement problem : P_11.
[18:09:03] exhaustive.py (line 153):     INFO: Merging sub-alignments for placement problem : P_12.
[18:09:03] exhaustive.py (line 153):     INFO: Merging sub-alignments for placement problem : P_13.
[18:09:03] exhaustive.py (line 153):     INFO: Merging sub-alignments for placement problem : P_14.
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/axodines/assemblycomparator2/conda_base/64695b6c37f59a4845639768395efc51_/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/home/axodines/assemblycomparator2/conda_base/64695b6c37f59a4845639768395efc51_/lib/python3.7/site-packages/sepp/scheduler.py", line 74, in __call__
    return self.run()
  File "/home/axodines/assemblycomparator2/conda_base/64695b6c37f59a4845639768395efc51_/lib/python3.7/site-packages/sepp/jobs.py", line 154, in run
    if self.read_stderr() else 'No error messages available']))
sepp.scheduler.JobError: The following execution failed:
/home/axodines/assemblycomparator2/conda_base/64695b6c37f59a4845639768395efc51_/bin/pplacer --out-dir /home/axodines/assemblycomparator2/tests/MAGs/results_ac2/samples/Treatment_LowE.metabat.461/busco/auto_lineage/run_
bacteria_odb10/sepp_tmp_files/output.gv3gkm6m/root/P_0 -j 1 -r /home/axodines/assemblycomparator2/tests/MAGs/results_ac2/samples/Treatment_LowE.metabat.461/busco/auto_lineage/run_bacteria_odb10/sepp_tmp_files/output.gv3gkm6m/root/P_0/pplacer.backbone.f0suopvv.fasta -s /home/axodines/assemblycomparator2/databases/busco/placement_files/tree_metadata.bacteria_odb10.2019-12-16.txt -t /home/axodines/assemblycomparator2/tests/MAGs/results_ac2/samples/Treatment_LowE.metabat.461/busco/auto_lineage/run_bacteria_odb10/sepp_tmp_files/output.gv3gkm6m/root/P_0/pplacer.tree.zrgc8skr.tre --groups 10 /home/axodines/assemblycomparator2/tests/MAGs/results_ac2/samples/Treatment_LowE.metabat.461/busco/auto_lineage/run_bacteria_odb10/sepp_tmp_files/output.gv3gkm6m/root/P_0/pplacer.extended.0.brzi1unn.fasta
No error messages available
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/axodines/assemblycomparator2/conda_base/64695b6c37f59a4845639768395efc51_/bin/run_sepp.py", line 26, in <module>
    ExhaustiveAlgorithm().run()
  File "/home/axodines/assemblycomparator2/conda_base/64695b6c37f59a4845639768395efc51_/lib/python3.7/site-packages/sepp/algorithm.py", line 175, in run
    if not JobPool().wait_for_all_jobs():
  File "/home/axodines/assemblycomparator2/conda_base/64695b6c37f59a4845639768395efc51_/lib/python3.7/site-packages/sepp/scheduler.py", line 366, in wait_for_all_jobs
    result.get()
  File "/home/axodines/assemblycomparator2/conda_base/64695b6c37f59a4845639768395efc51_/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
sepp.scheduler.JobError: The following execution failed:
/home/axodines/assemblycomparator2/conda_base/64695b6c37f59a4845639768395efc51_/bin/pplacer --out-dir /home/axodines/assemblycomparator2/tests/MAGs/results_ac2/samples/Treatment_LowE.metabat.461/busco/auto_lineage/run_bacteria_odb10/sepp_tmp_files/output.gv3gkm6m/root/P_0 -j 1 -r /home/axodines/assemblycomparator2/tests/MAGs/results_ac2/samples/Treatment_LowE.metabat.461/busco/auto_lineage/run_bacteria_odb10/sepp_tmp_files/output.gv3gkm6m/root/P_0/pplacer.backbone.f0suopvv.fasta -s /home/axodines/assemblycomparator2/databases/busco/placement_files/tree_metadata.bacteria_odb10.2019-12-16.txt -t /home/axodines/assemblycomparator2/tests/MAGs/results_ac2/samples/Treatment_LowE.metabat.461/busco/auto_lineage/run_bacteria_odb10/sepp_tmp_files/output.gv3gkm6m/root/P_0/pplacer.tree.zrgc8skr.tre --groups 10 /home/axodines/assemblycomparator2/tests/MAGs/results_ac2/samples/Treatment_LowE.metabat.461/busco/auto_lineage/run_bacteria_odb10/sepp_tmp_files/output.gv3gkm6m/root/P_0/pplacer.extended.0.brzi1unn.fasta
No error messages available
```

**Comment by cmkobel** [comment]
> After a bit more investigation along with our sys admin it turns out the problem may be with the particular machine I was using being unable to handle the instructions from the bundled pplacer binary in the SEPP conda package. The pplacer binary depends on an old version of ocaml and ocaml is not great at keeping backward compatibility. Hence it doesn't work on that particular machine.
> 
> We have managed to get it to work on several other machines though, so there doesn't seem to be anything critical with the SEPP package. I'll close this issue.

@berkelem, were you able to find a fix? I'm seeing this same error on two very different systems.
