### ISSUE TITLE
Depends on python=3.1 ?

### ISSUE THREAD

**Issue by geboro** [smirarab/sepp#115]
Hello, I keep having the following error installing sepp from its conda recipe: 

ResolvePackageNotFound: 
  - python=3.1

Is this really the case? that is a pretty old version...

**Comment by sjanssen2** [comment]
Hi @geboro, which channel do you use? I would recommend bioconda. There, we ask for 3.7:
https://github.com/bioconda/bioconda-recipes/blob/d69c672162d767a323bdbbc0ebe80b5e88302f31/recipes/sepp/meta.yaml#L22

**Comment by sjanssen2** [comment]
I am seeing similar issues in totally unrelated conda packages. It might be due to the new python version `3.10` which might be resolved to `3.1` if you interpret it as a floating point number?!

**Comment by sjanssen2** [comment]
https://stackoverflow.com/questions/69481608/cannot-set-up-a-conda-environment-with-python-3-10

**Comment by sjanssen2** [comment]
this issue can be closed @smirarab
