### ISSUE TITLE
Dendropy v4.6.0 causing SEPP to break

### ISSUE THREAD

**Issue by berkelem** [smirarab/sepp#125]
A new version of Dendropy was released a week ago and it is causing the SEPP conda build to break. Could you look into this and either update SEPP to maintain compatibility or update the conda recipe to restrict it to older versions of Dendropy?

**Comment by ncolaian** [comment]
I think I am having the same problem. I keep getting this error - 
`ImportError: cannot import name '_convert_node_to_root_polytomy' from 'dendropy.datamodel.treemodel'`

**Comment by lh3** [comment]
CC @mmore500

**Comment by mmore500** [comment]
Taking a look!

**Comment by ac-simpson** [comment]
A note for those coming here to solve their sepp issue (as I did today) - I had dendropy installed both via conda and pip, and so downgrading dendropy via conda didn't work until I uninstalled the pip version as well. (look at "conda list" vs "pip list").

**Comment by nicolo-tellini** [comment]
Hello, 

I am having the same issue :
` ImportError: cannot import name '_convert_node_to_root_polytomy' from 'dendropy.datamodel.treemodel'`

any solution for that ?

**Comment by mmore500** [comment]
Hi @nicolo-tellini 

Pinning `dendropy==4.5.2` within your runtime environment should fix this issue. You’l need to use your package manager (pip, poetry, conda, etc.) to accomplish this.

**Comment by nicolo-tellini** [comment]
Hi @mmore500 ,

thank you very much it works nicely 

best

nic

**Comment by smirarab** [comment]
@mmore500 Thanks a ton for your PR and sorry I am so slow these days with these. I hope the merged PR fixes the issue?

**Comment by mmore500** [comment]
Yes! Thank you @smirarab :)

**Comment by smirarab** [comment]
I also decided to make sepp backward compatible with dendropy <4.5.2. Fixed in 4.5.5. b3b3305
