### ISSUE TITLE
java.lang.NumberFormatException: null when running sepp

### ISSUE THREAD

**Issue by elena-iri** [smirarab/sepp#134]
I'm trying to run the following command in order to generate the alignment of fragments to a reference msa:

run_sepp.py -m amino -t RAxML_tree -r RAxML_info -a repSeq_msa_trim_qcov80.fa -f seqs.fa

I'm getting the following error and I'm lost as to how to fix it or what the problem is:

Exception in thread "main" java.lang.NumberFormatException: null
	at java.lang.Integer.parseInt(Integer.java:542)
	at java.lang.Integer.<init>(Integer.java:867)
	at phylolab.taxonamic.PPlacerJSONMerger.relabelJson(PPlacerJSONMerger.java:172)
	at phylolab.taxonamic.PPlacerJSONMerger.main(PPlacerJSONMerger.java:288)

I'm running this is an anaconda3 environment, with the following software versions:
- dendropy 4.5.2
- pyhton 3.7
- openjdk 1.8.0_152-release (before I tried with openjdk 11.0.13 and got the same error)
- RAXML 8.2.12 (I generated the info file following the same steps that were used to resolve the issue "SEPP: pplacer error with RAxML info file #40" by the user taylorreiter) 
- I also previously used the command "export LC_ALL=C" as I was getting an error due to different languages in the local variables

I would be very grateful if anyone could shine some light on what the problem may be.
Thank you in advance.

**Comment by smirarab** [comment]
Do you think you could share the files (either through or outside github) so that I can reproduce?

**Comment by elena-iri** [comment]
Thank you for your response! I will send them to you via email.

**Comment by elena-iri** [comment]
I'm closing this issue as I accessed a pre-installed version of sepp on another computer and had no issues with my files. I believe my problem was related to installing sepp.
