### ISSUE TITLE
SEPP: pplacer jobs fail when fragments share common IDs with the reference sequences/tree

### ISSUE THREAD

**Issue by alicedb2** [smirarab/sepp#33]
pplacer jobs fail when fragments share common IDs with the reference sequences/tree.

I'd suggest SEPP to simply raise an error at load time if the set intersection between fragment and reference IDs isn't empty.

This is I believe the same as the second issue raised in [https://github.com/smirarab/sepp/issues/26](https://github.com/smirarab/sepp/issues/26).

**Comment by sjanssen2** [comment]
added PR #36 to address this issue

**Comment by sjanssen2** [comment]
@smirarab I think we can close this issue now
