### ISSUE TITLE
UPP: pasta should be run *without* the --auto option

### ISSUE THREAD

**Issue by smirarab** [smirarab/sepp#7]
UPP runs PASTA with --auto option. It should not. Using --auto is depreciated in PASTA, and causes at least one bug. It resulting in ignoring --num-cpus provided to PASTA. So, even if UPP is run with 2 cpus, PASTA will use all the available CPUs.

**Comment by namphuon** [comment]
The --auto has been removed from the PastaAlignJob from job.py
