### ISSUE TITLE
error in run-sepp.sh

### ISSUE THREAD

**Issue by pamelacamejo** [smirarab/sepp#71]
Script does not define rxi (tax info file) correctly. Change
alg="$DIR/ref/RAxML_info-reference-gg-raxml-bl.info"
by
rxi="$DIR/ref/RAxML_info-reference-gg-raxml-bl.info"

**Comment by smirarab** [comment]
fixed in 74ceabbc7ae8f3293196728d3d970da459b8be30.
Thanks for the report.
