### ISSUE TITLE
UPP: adjust the percent around N for defining fragments. 

### ISSUE THREAD

**Issue by smirarab** [smirarab/sepp#8]
We need an option to enable saying that X% below and Y% above N are fragments. We can default these to 75 and 125, but we need to give the user a chance to change these.

**Comment by namphuon** [comment]
I have added the -T flag that allows this.

-T N, --backbone_threshold N
                        Only consider sequences with lengths within (1-N)*M
                        and (1+N)*M as full-length, where M is the
                        median.[default: 0.25]
